apiVersion: v1
kind: ConfigMap
metadata:
  name: sav-config
  namespace: sav-pro
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  DATABASE_AUTO_MIGRATE: "true"
  JWT_ISSUER: "AuthService"
  JWT_AUDIENCE: "AuthServiceUsers"
  SEED_ENABLED: "true"
  SEED_DEMO_DATA: "true"
  RESET_DEMO_DATA: "true"
  SEED_ADMIN_EMAIL: "admin@savpro.local"
  SEED_ADMIN_FIRSTNAME: "Admin"
  SEED_ADMIN_LASTNAME: "User"
  SEED_ADMIN_PHONE: "0000000000"
  NOTIFICATIONS_ADMIN_EMAIL: "admin@savpro.local"
  AUTH_RATE_LIMIT_PER_MINUTE: "10"
  UPLOAD_RATE_LIMIT_PER_MINUTE: "20"
---
apiVersion: v1
kind: Secret
metadata:
  name: sav-secrets
  namespace: sav-pro
type: Opaque
stringData:
  SA_PASSWORD: "PfeNet!2026Strong"
  RABBITMQ_USER: "pfe"
  RABBITMQ_PASS: "PfeNetRabbit!2026"
  JWT_SECRET: "PfeNet_Local_Development_Jwt_Secret_2026_Minimum_32_Chars"
  SEED_ADMIN_PASSWORD: "Password123!"
