import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock, Filter, MapPin, Phone, Plus, Send, User, UserPlus, Wrench, X, RefreshCw, Loader2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { CalendarWeek } from '../components/calendar/CalendarWeek';
import { ApiErrorState } from '../components/common/ApiErrorState';
import { Avatar, Badge, Button, Card, Field, IconButton, Modal } from '../components/ui';
import { usePlanning } from '../hooks/usePlanning';
import { useUsers } from '../hooks/useUsers';
import { getFriendlyApiError } from '../utils/errorMessages';

const requestTabs = ['All', 'Proposed', 'Pending'];

export function PlanningPage({ notify }) {
  const planning = usePlanning();
  const technicianResource = useUsers('Technician');
  const planningRequests = planning.planningRequests;
  const appointments = planning.appointments;
  const technicians = technicianResource.users;
  const [filter, setFilter] = useState('All');
  const [selectedRequestId, setSelectedRequestId] = useState('');
  const [selectedAppointmentId, setSelectedAppointmentId] = useState('');
  const [modal, setModal] = useState(null);
  const [form, setForm] = useState({ date: new Date().toISOString().slice(0, 10), start: '09:00', end: '10:30', technicianId: '', status: 'Proposed', note: '' });
  const [errors, setErrors] = useState({});

  const visibleRequests = useMemo(() => planningRequests.filter(row => filter === 'All' || row.status === filter), [planningRequests, filter]);
  const selectedRequest = planningRequests.find(item => item.id === selectedRequestId) || visibleRequests[0] || planningRequests[0];
  const selectedAppointment = appointments.find(item => item.id === selectedAppointmentId) || appointments[0];

  useEffect(() => {
    if (!selectedRequestId && planningRequests[0]) setSelectedRequestId(planningRequests[0].id);
  }, [planningRequests, selectedRequestId]);

  useEffect(() => {
    if (!selectedAppointmentId && appointments[0]) setSelectedAppointmentId(appointments[0].id);
  }, [appointments, selectedAppointmentId]);

  function openAppointmentModal() {
    setForm(current => ({ ...current, requestId: selectedRequest?.id || '', technicalRequestId: selectedRequest?.technicalId || '', technicianId: technicians[0]?.id || '' }));
    setErrors({});
    setModal('appointment');
  }

  async function submitAppointment(event) {
    event.preventDefault();
    const nextErrors = {
      requestId: form.requestId ? '' : 'Planning request is required.',
      date: form.date ? '' : 'Date is required.',
      start: form.start ? '' : 'Start time is required.',
      end: form.end ? '' : 'End time is required.',
      technicianId: form.technicianId ? '' : 'Technician is required.'
    };
    setErrors(nextErrors);
    if (Object.values(nextErrors).some(Boolean)) return;
    try {
      const request = planningRequests.find(row => row.id === form.requestId) || selectedRequest;
      const appointment = await planning.createAppointment({ ...form, technicalRequestId: request?.technicalId || form.technicalRequestId });
      if (form.technicianId) {
        const tech = technicians.find(row => String(row.id) === String(form.technicianId));
        await planning.assignTechnician(appointment.technicalId || appointment.id, tech);
      }
      setSelectedAppointmentId(appointment.id);
      setModal(null);
      notify('Appointment created successfully');
    } catch (err) {
      notify(getFriendlyApiError(err), 'error');
    }
  }

  async function changeStatus(status) {
    if (!selectedAppointment) return;
    try {
      if (status === 'Confirmed') await planning.confirmAppointment(selectedAppointment.technicalId || selectedAppointment.id);
      else if (status === 'Cancelled') await planning.cancelAppointment(selectedAppointment.technicalId || selectedAppointment.id, 'Cancelled from SAV Pro UI');
      else notify(`${status} requires its dedicated backend workflow`, 'error');
      notify(`Appointment marked ${status}`);
    } catch (err) {
      notify(getFriendlyApiError(err), 'error');
    }
  }

  async function submitReschedule(event) {
    event.preventDefault();
    try {
      await planning.rescheduleAppointment(selectedAppointment.technicalId || selectedAppointment.id, form);
      setModal(null);
      notify('Appointment rescheduled');
    } catch (err) {
      notify(getFriendlyApiError(err), 'error');
    }
  }

  function publishNotification() {
    notify('Notifications are now generated by backend events after appointment operations.');
  }

  async function assignTechnician(technicianId) {
    const technician = technicians.find(item => String(item.id) === String(technicianId));
    if (!selectedAppointment) return;
    try {
      await planning.assignTechnician(selectedAppointment.technicalId || selectedAppointment.id, technician);
      setModal(null);
      notify('Technician assigned to appointment');
    } catch (err) {
      notify(getFriendlyApiError(err), 'error');
    }
  }

  const loadError = planning.error || technicianResource.error;
  const loadErrorStatus = planning.errorStatus || technicianResource.errorStatus;
  const loading = planning.loading || technicianResource.loading;

  return (
    <section className="page-shell planning-page">
      <div className="page-title-row"><div><h1>Planning Center</h1><p>Plan, assign and manage appointments across technicians.</p></div></div>
      {loadError && <Card><ApiErrorState status={loadErrorStatus} message={loadError} onRetry={() => { planning.reload(); technicianResource.reload(); }} /></Card>}
      <div className="planning-layout">
        <Card className="planning-requests-panel" title="Planning Requests" actions={<><Badge tone="count">{planningRequests.length}</Badge><IconButton icon={Filter} label="Filter requests" className="ghost" onClick={() => notify('Planning request filters are available in the tabs below')} /></>}>
          <div className="mini-tabs">{requestTabs.map(tab => <button type="button" key={tab} className={filter === tab ? 'active' : ''} onClick={() => setFilter(tab)}>{tab} <span>{tab === 'All' ? planningRequests.length : planningRequests.filter(item => item.status === tab).length}</span></button>)}</div>
          <div className="request-card-list">
            {loading && <div className="empty-state"><Loader2 size={18} /> Loading planning data...</div>}
            {!loading && visibleRequests.map(request => <button type="button" key={request.id} className={`planning-request-card ${selectedRequest?.id === request.id ? 'active' : ''}`} onClick={() => setSelectedRequestId(request.id)}><div className="request-card-head"><strong>{request.id}</strong><Badge>{request.priority}</Badge></div><RequestLine icon={User}>{request.client}</RequestLine><RequestLine icon={Wrench}>{request.product}</RequestLine><RequestLine icon={MapPin}>{request.location}</RequestLine><RequestLine icon={CalendarDays}>{request.date}</RequestLine><Badge>{request.status}</Badge></button>)}
          </div>
          <div className="panel-footer">Showing 1 to {visibleRequests.length} of {planningRequests.length} requests</div>
        </Card>
        <Card className="calendar-panel">
          <div className="calendar-toolbar"><div className="segmented"><button type="button" className="active" onClick={() => notify('Week view selected')}>Week</button><button type="button" onClick={() => notify('Month view ready')}>Month</button><button type="button" onClick={() => notify('Agenda view ready')}>Agenda</button></div><div className="calendar-nav"><IconButton icon={ChevronLeft} label="Previous week" onClick={() => notify('Previous week')} /><IconButton icon={ChevronRight} label="Next week" onClick={() => notify('Next week')} /><Button size="sm" onClick={() => notify('Today selected')}>Today</Button></div><h2>Backend planning calendar</h2><Button icon={Filter} onClick={() => notify('Calendar filters opened')}>Filters</Button><Button variant="primary" icon={Plus} onClick={openAppointmentModal}>New Appointment</Button></div>
          <section className="availability-strip"><h3>Technician Availability</h3><div className="availability-list">{technicians.map(tech => <div className="availability-chip" key={tech.id}><Avatar name={tech.name} initials={tech.name} size="md" /><span><strong>{tech.name}</strong><small>{tech.email}</small></span><Badge tone="success">Backend</Badge></div>)}</div></section>
          <CalendarWeek appointments={appointments} />
          <div className="calendar-legend">{technicians.slice(0, 5).map(tech => <span key={tech.id}><i className="legend-dot blue" />{tech.name}</span>)}</div>
        </Card>
        {selectedAppointment && <Card className="appointment-details-panel" title="Appointment Details" actions={<IconButton icon={X} label="Close appointment details" className="ghost" onClick={() => notify('Appointment details kept visible')} />}>
          <div className="appointment-id-row"><Badge>{selectedAppointment.status}</Badge><strong>#{selectedAppointment.id}</strong></div><h2>{selectedAppointment.client}</h2><p>{selectedAppointment.product}</p>
          <div className="detail-list"><RequestLine icon={CalendarDays}>{selectedAppointment.date}</RequestLine><RequestLine icon={Clock}>{selectedAppointment.start} - {selectedAppointment.end}</RequestLine><RequestLine icon={Clock}>Planned Duration <strong>{selectedAppointment.duration}</strong></RequestLine></div>
          <section className="detail-section"><h3>Client</h3><p>{selectedAppointment.client}</p><RequestLine icon={Phone}>Backend contact</RequestLine></section>
          <section className="detail-section"><h3>Service Address</h3><p>{selectedAppointment.location}</p><button type="button" className="link-button" onClick={() => notify('Map link opened')}><MapPin size={15} /> View on map</button></section>
          <section className="technician-mini-card"><Avatar name={selectedAppointment.technicianName || 'Unassigned'} initials={selectedAppointment.technicianName} size="lg" /><div><strong>{selectedAppointment.technicianName || 'Unassigned'}</strong><span>Backend assignment</span></div><Badge tone="success">Available</Badge></section>
          <section className="detail-section"><h3>Customer Presence</h3><RequestLine icon={User}>{selectedAppointment.customerPresence ? 'Required' : 'Optional'}</RequestLine></section>
          <section className="detail-section note"><h3>Planning Note</h3><p>{selectedAppointment.note}</p></section>
          <section className="status-button-group"><h3>Status</h3><div>{['Proposed', 'Confirmed', 'Rescheduled', 'Completed'].map(item => <Button key={item} size="sm" variant={selectedAppointment.status === item ? 'success' : 'secondary'} onClick={() => changeStatus(item)}>{item}</Button>)}<Button size="sm" icon={Check} onClick={() => changeStatus('Confirmed')}></Button></div></section>
          <div className="appointment-actions"><Button icon={UserPlus} onClick={() => setModal('assign')}>Assign Technician</Button><Button icon={CalendarDays} onClick={() => { setForm({ ...form, date: selectedAppointment.date, start: selectedAppointment.start, end: selectedAppointment.end }); setModal('reschedule'); }}>Reschedule</Button><Button variant="primary" icon={Send} rightIcon={ChevronRight} onClick={publishNotification}>Publish Notification</Button></div>
        </Card>}
      </div>
      {modal === 'appointment' && <AppointmentModal title="New Appointment" planningRequests={planningRequests} technicians={technicians} form={form} setForm={setForm} errors={errors} onClose={() => setModal(null)} onSubmit={submitAppointment} />}
      {modal === 'reschedule' && <AppointmentModal title="Reschedule Appointment" planningRequests={planningRequests} technicians={technicians} form={form} setForm={setForm} errors={errors} onClose={() => setModal(null)} onSubmit={submitReschedule} hideRequest />}
      {modal === 'assign' && <Modal title="Assign Technician" onClose={() => setModal(null)}><div className="request-card-list">{technicians.map(technician => <button type="button" key={technician.id} className="planning-request-card" onClick={() => assignTechnician(technician.id)}><div className="request-card-head"><strong>{technician.name}</strong><Badge tone="success">Backend</Badge><UserPlus size={17} /></div><RequestLine icon={Wrench}>{technician.role}</RequestLine><RequestLine icon={Phone}>{technician.email}</RequestLine></button>)}</div></Modal>}
    </section>
  );
}

function AppointmentModal({ title, planningRequests, technicians, form, setForm, errors, onClose, onSubmit, hideRequest = false }) {
  return <Modal title={title} onClose={onClose} footer={<><Button onClick={onClose}>Cancel</Button><Button variant="primary" icon={CalendarDays} onClick={onSubmit}>Save Appointment</Button></>}><form className="form-grid" onSubmit={onSubmit}>{!hideRequest && <Field label="Planning Request" error={errors.requestId}><select value={form.requestId || ''} onChange={event => setForm(current => ({ ...current, requestId: event.target.value }))}><option value="">Select request</option>{planningRequests.map(request => <option key={request.id} value={request.id}>{request.id} - {request.client}</option>)}</select></Field>}<Field label="Technician" error={errors.technicianId}><select value={form.technicianId || ''} onChange={event => setForm(current => ({ ...current, technicianId: event.target.value }))}><option value="">Select technician</option>{technicians.map(technician => <option key={technician.id} value={technician.id}>{technician.name}</option>)}</select></Field><Field label="Date" error={errors.date}><input type="date" value={form.date || ''} onChange={event => setForm(current => ({ ...current, date: event.target.value }))} /></Field><Field label="Start" error={errors.start}><input type="time" value={form.start || ''} onChange={event => setForm(current => ({ ...current, start: event.target.value }))} /></Field><Field label="End" error={errors.end}><input type="time" value={form.end || ''} onChange={event => setForm(current => ({ ...current, end: event.target.value }))} /></Field><Field label="Status"><select value={form.status || 'Proposed'} onChange={event => setForm(current => ({ ...current, status: event.target.value }))}><option>Proposed</option><option>Confirmed</option><option>Rescheduled</option><option>Completed</option></select></Field><Field label="Planning Note"><textarea value={form.note || ''} onChange={event => setForm(current => ({ ...current, note: event.target.value }))} /></Field></form></Modal>;
}
function RequestLine({ icon: Icon, children }) { return <span className="request-line"><Icon size={15} />{children}</span>; }
